version: "3.7"

services:
  webmin:
    build: .
    container_name: webmin
    ports:
      - "10000:10000"
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/webmin:/etc/webmin
      - /var/run/docker.sock:/var/run/docker.sock
