version: "3.7"

services:
  webmin:
    build: .
    container_name: webmin
    ports:
      - "10000:10000"
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - webmin_data:/etc/webmin

volumes:
  webmin_data:
